# Sample config file

# The theme colours can be an rgb string of the form "255, 255, 255" or a string that references the colours from your terminal theme: Reset, Black, Red, Green, Yellow, Blue, Magenta, Cyan, Gray, DarkGray, LightRed, LightGreen, LightYellow, LightBlue, LightMagenta, LightCyan, White.
theme:
  active: "119, 60, 53" # current playing song in list
  banner: "119, 60, 53" # the "spotify-tui" banner on launch
  error_border: Red # error dialog border
  error_text: LightRed # error message text (e.g. "Spotify API reported error 404")
  hint: Yellow # hint text in errors
  hovered: "161, 90, 52" # hovered pane border
  inactive: "183, 161, 119" # borders of inactive panes
  playbar_background: Black # background of progress bar
  playbar_progress: "183, 161, 119" # filled-in part of the progress bar
  playbar_progress_text: "223, 225, 216" # song length and time played/left indicator in the progress bar
  playbar_text: "223, 255, 216" # artist name in player pane
  analysis_bar: "161, 90, 52" # analysis bar
  analysis_bar_text: "223, 225, 216"
  selected: "119, 60, 53" # a) selected pane border, b) hovered item in list, & c) track title in player
  text: "223, 225, 216" # text in panes
  header: "223, 225, 216" # header text in panes (e.g. 'Title', 'Artist', etc.)
